### ISSUE TITLE
When the sourcemap in build mode is true， the source file cannot be generated correctly

### ISSUE THREAD

**Issue by feifeilian** [originjs/vite-plugin-federation#355] opened 2023-02-16 07:48 UTC
When the sourcemap in build mode is true， the source file cannot be generated correctly.
the plugin version is 1.2.0  Hope to solve this problem.
<img width="569" alt="image" src="https://user-images.githubusercontent.com/26051793/219300163-4f22087c-6817-485d-9e74-0c19a035f793.png">
<img width="1367" alt="image" src="https://user-images.githubusercontent.com/26051793/219300533-a05bb051-41aa-4639-aa13-23d5e812256b.png">

**Comment by includeios** [comment] 2023-02-23 07:51
i have the same issue. recording to previous topic this issure has been fixed by this commit: https://github.com/originjs/vite-plugin-federation/pull/232.  @ruleeeer 

i install the latest version: 1.2.1 but still log this warning on building:
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/18004081/220849146-cd4ffe15-e3de-41c7-814c-f539f62d4454.png">

environment: node18 & pnpm7

**Comment by includeios** [comment] 2023-03-06 07:25
Hi, @ruleeeer  i would if this issue is being fixed. and i find the problem is [in this line of code: ](https://github.com/originjs/vite-plugin-federation/blob/90d0e5d54cf0ee4c20eff95b58bbce51b3d00ea8/packages/lib/src/prod/remote-production.ts#L458)

Since we use `magicString.prepend` to modified the original code, we must generate modified code to newest sourcemap

i pull  a commit [like this](https://github.com/originjs/vite-plugin-federation/pull/366).  Looking forward to your reply

**Comment by ruleeeer** [comment] 2023-03-23 07:30
It seems that this problem has been fixed by @includeios. I will close this issue as scheduled. If you have any questions later, please open it.

**Closed by ruleeeer** 2023-03-23 07:30 UTC
Labels: bug
