### ISSUE TITLE
Issue with Chrome

### ISSUE THREAD

**Issue by tathje** [originjs/vite-plugin-federation#630] opened 2024-09-20 04:46 UTC
### Versions

- vite-plugin-federation: ^1.3.6
- vite: ^5.46

### Steps to reproduce
- CMD `git clone git@github.com:originjs/vite-plugin-federation.git`
- CMD `cd vite-plugin-federation/packages/examples/react-vite`
- CMD `pnpm install`
- CMD `pnpm run build:remotes && pnpm run serve:remotes`
- CMD `pnpm run dev:hosts`
- open `http://localhost:5000/`

### What is actually happening?

- `vite dev` (host app) not working on Chrome (v128 ~ v129) but still working on `vite build` and another browser

**Comment by AlexThurston** [comment] 2024-09-20 17:42
I can confirm that this is happening on other Chromium based browsers like Arc and Brave, but things are working correctly on Safari.

There doesn't appear to be any logs or errors in the browser dev console either.

I did notice that the div ends up empty in the browsers that don't work.

![image](https://github.com/user-attachments/assets/02dc935f-4d56-47a3-b398-000b1eae0a07)

**Comment by AlexThurston** [comment] 2024-09-20 19:22
Related to https://github.com/antfu/repro-chrome-v129 perhaps?

**Comment by ahatton-hpt** [comment] 2024-09-24 07:37
@n-anilrathod 

> Related to https://github.com/antfu/repro-chrome-v129 perhaps?

I believe @AlexThurston is correct. After investigating, this issue only seems to occur when HMR is enabled. Disabling HMR in development resolves the issue, but at the cost of losing Hot Reload functionality. It appears that this Chrome bug is fixed in the upcoming v130 release. I tested the beta version of Chrome with HMR enabled, and it worked without issues.

I have not encountered any problems with production builds or deployments—this only happens for me during development when Vite is running as a server with HMR enabled.

**Comment by SkyWalker653** [comment] 2024-09-24 08:51
I am using [vite-plugin-top-level-await](https://github.com/Menci/vite-plugin-top-level-await) plugin as a temporary workaround.

**Comment by n-anilrathod** [comment] 2024-09-24 12:58
> @n-anilrathod
> 
> > Related to https://github.com/antfu/repro-chrome-v129 perhaps?
> 
> I believe @AlexThurston is correct. After investigating, this issue only seems to occur when HMR is enabled. Disabling HMR in development resolves the issue, but at the cost of losing Hot Reload functionality. It appears that this Chrome bug is fixed in the upcoming v130 release. I tested the beta version of Chrome with HMR enabled, and it worked without issues.
> 
> I have not encountered any problems with production builds or deployments—this only happens for me during development when Vite is running as a server with HMR enabled.

@ahatton-hpt, the issue was not related to HMR as initially thought. It appears to be linked to circular imports, similar to what's described here: https://github.com/antfu/repro-chrome-v129. To resolve the issue, I added the [vite-plugin-top-level-await](https://github.com/Menci/vite-plugin-top-level-await), which seems to fix it. However, this plugin is considered optional for the latest Chrome versions. While the issue is temporarily resolved, I hope we won't encounter similar problems in the future.

**Comment by RafaDev-gft** [comment] 2024-09-25 15:31
It does not work for me, I am importing the library and I put the configuration in my vite.config.ts like this, am I doing something wrong?
```
export default defineConfig({
  plugins: [
    topLevelAwait({
      promiseExportName: "__tla",
      promiseImportName: i => `__tla_${i}`
    }),
    react(),
    federation({
      name: "remote-user-management",
      filename: "remoteEntry.js",
      remotes: {
        remoteUtilities: "http://localhost:5001/assets/remoteEntry.js",
      },
```

**Comment by namnh99** [comment] 2024-10-15 04:52
> I am using [vite-plugin-top-level-await](https://github.com/Menci/vite-plugin-top-level-await) plugin as a temporary workaround.
I added but didn't work, could you provide me steps to do this? thanks

**Comment by tathje** [comment] 2024-10-23 15:26
This issue has been resolved on chrome 130

**Closed** 2024-10-23 15:26 UTC
